{
 "title": "Linux Host Metrics",
 "description": "Linux Host Metrics for Zycus",
 "tags": [ "linux" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": "{*}" },
   { "name": "group", "label": "Group", "query": "{*}" },
   { "name": "host", "query": "{$env: $group}{*}" },
   {
    "name": "fs",
    "label": "FS filter",
    "query": {}
   },
   {
    "name": "disk",
    "label": "Disk filter",
    "query": {}
   },
   { "name": "netif", "label": "Netif" },
   { "name": "interval", "label": "Interval", "query": "1m,5m,15m,1h,1d" }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM available",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Available memory in %" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Filesystem (Space utilization %)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Filesystem./" },
     "functions": [
      {
       "$$hashKey": "object:3413",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/: Space utilization/",
        "$'"
       ],
       "text": "replaceAlias(/: Space utilization/, $')"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Space utilization/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Agent status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Zabbix agent ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU cores (Total)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of CPUs" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default"
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "$$hashKey": "object:1227",
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5m",
        "avg"
       ],
       "text": "groupBy(5m, avg)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU utilization" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SWAP (Total)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total swap space" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zabbix alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "type": "alexanderzobnin-zabbix-triggers-panel",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "application": { "filter": "/.*/" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "" },
       "options": {
        "acknowledged": 2,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 0,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default"
       },
       "proxy": { "filter": "" },
       "showProblems": "problems",
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "/.*/" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Basic metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization, %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "CPU" },
       "functions": [
        {
         "$$hashKey": "object:930",
         "def": {
          "category": "Trends",
          "defaultParams": [ "avg" ],
          "name": "trendValue",
          "params": [
           {
            "name": "type",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "max" ],
         "text": "trendValue(max)"
        },
        {
         "$$hashKey": "object:931",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/:.+$/",
          " "
         ],
         "text": "replaceAlias(/:.+$/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "CPU utilization" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Memory available, GiB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "Memory" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Available memory" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Memory" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Total memory" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "CPU iowait time, %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "CPU" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/:.+$/",
          " "
         ],
         "text": "replaceAlias(/:.+$/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "CPU iowait time" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Load Average 1/5/15 min (total all cores)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "CPU" },
       "functions": [
        {
         "$$hashKey": "object:846",
         "def": {
          "category": "Trends",
          "defaultParams": [ "avg" ],
          "name": "trendValue",
          "params": [
           {
            "name": "type",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "max" ],
         "text": "trendValue(max)"
        },
        {
         "$$hashKey": "object:847",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/:.+$/",
          " "
         ],
         "text": "replaceAlias(/:.+$/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Load average (1m avg)" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "CPU" },
       "functions": [
        {
         "$$hashKey": "object:942",
         "def": {
          "category": "Trends",
          "defaultParams": [ "avg" ],
          "name": "trendValue",
          "params": [
           {
            "name": "type",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "max" ],
         "text": "trendValue(max)"
        },
        {
         "$$hashKey": "object:943",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/:.+$/",
          " "
         ],
         "text": "replaceAlias(/:.+$/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Load average (5m avg)" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "CPU" },
       "functions": [
        {
         "$$hashKey": "object:971",
         "def": {
          "category": "Trends",
          "defaultParams": [ "avg" ],
          "name": "trendValue",
          "params": [
           {
            "name": "type",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "max" ],
         "text": "trendValue(max)"
        },
        {
         "$$hashKey": "object:972",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/:.+$/",
          " "
         ],
         "text": "replaceAlias(/:.+$/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Load average (15m avg)" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization, %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "CPU" },
       "functions": [
        {
         "def": {
          "category": "Trends",
          "defaultParams": [ "avg" ],
          "name": "trendValue",
          "params": [
           {
            "name": "type",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "max" ],
         "text": "trendValue(max)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/^CPU (nice|steal|idle|system|user|iowait) time/"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Memory available, bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Available memory" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Number of processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "General" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Number of processes" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "OS settings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "General" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Maximum number of open file descriptors"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "General" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Maximum number of processes" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "File Systems capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space (GiB)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "$fs" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/(Total space)/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "$fs" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/(Used space)/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Free Inodes (percentage)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "$fs" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/(Free inodes)/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  { "title": "Disk Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "application": { "filter": "Disk Performance" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Write:Ops per second/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Write Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "$disk" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Disk write rate/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Write Latency (all ops)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Write:ms/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "application": { "filter": "Disk Performance" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Read:Ops per second/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Read req/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "application": { "filter": "$disk" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/(read)/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Read Latency (all ops)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "Disk Performance" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Read:ms/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network IN",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "application": { "filter": "$netif" },
       "functions": [
        {
         "$$hashKey": "object:3723",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Incoming network traffic on /",
          " "
         ],
         "text": "replaceAlias(/Incoming network traffic on /,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Bits (received|sent)/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Network IN dropped and errors pps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "application": { "filter": "$netif" },
       "functions": [
        {
         "$$hashKey": "object:3909",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Incoming network traffic/",
          " "
         ],
         "text": "replaceAlias(/Incoming network traffic/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/Inbound packets (discarded|with errors)/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Network OUT dropped and errors pps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "application": { "filter": "$netif" },
       "functions": [
        {
         "$$hashKey": "object:4034",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Outgoing network traffic/",
          " "
         ],
         "text": "replaceAlias(/Outgoing network traffic/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/Outbound packets (discarded|with errors)/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Swap %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Free swap space in %" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Zabbix agent details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "dtdhms" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "System uptime" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Zabbix agent availability",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "Monitoring agent" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Zabbix agent ping" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}