{
 "title": "PostgreSQL base metrics",
 "description": "Grafana dashboard for Mamonsu",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": {}
   },
   {
    "name": "group",
    "label": "Group",
    "query": {}
   },
   {
    "name": "host",
    "label": "Host",
    "query": {}
   },
   {
    "name": "database",
    "label": "Database",
    "query": {}
   },
   { "name": "limit", "label": "Queries limit", "query": "5,10,20,30,40,50,100,200" }
  ]
 },
 "panels": [
  { "title": "Database overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PostgreSQL: replica status" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DB uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PostgreSQL: service uptime" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PostgreSQL: cache hit ratio" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "WAL count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "PostgreSQL: count of xlog files"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Database size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Database $database: size" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Streaming replication lag (time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 1 },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Transform",
        "defaultParams": [],
        "name": "rate",
        "params": []
       },
       "params": [],
       "text": "rate()"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Delta of total lag for .*/" },
     "itemids": "Ti",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zabbix Agent",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Monitoring agent" },
     "functions": [
      {
       "def": {
        "category": "Special",
        "defaultParams": [ "avg" ],
        "name": "consolidateBy",
        "params": [
         {
          "name": "type",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "min" ],
       "text": "consolidateBy(min)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Zabbix agent ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Database active connections (count)",
   "type": "graph",
   "description": "PostgreSQL connections (max/total/active/idle/aborted)",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 3 },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "maximum connections" ],
       "text": "setAlias(maximum connections)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PostgreSQL: max connections" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "used connections" ],
       "text": "setAlias(used connections)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "PostgreSQL: number of total connections"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Database server ping (time)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 3 },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ping (ms)" ],
       "text": "setAlias(ping (ms))"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PostgreSQL: ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Mamonsu status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Mamonsu: plugin keep alive" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DB status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PostgreSQL: ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zabbix messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Problems",
     "type": "alexanderzobnin-zabbix-triggers-panel",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 10 },
     "targets": [
      {
       "application": { "filter": "/.*/" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "" },
       "options": {
        "acknowledged": 2,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 0,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default"
       },
       "proxy": { "filter": "" },
       "showProblems": "problems",
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL base metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections max/total/active/idle/aborted (count)",
     "type": "graph",
     "description": "PostgreSQL connections (max/total/active/idle/aborted)",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "total" ],
         "text": "setAlias(total)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: number of total connections"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "active" ],
         "text": "setAlias(active)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: number of active connections"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "idle" ],
         "text": "setAlias(idle)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: number of idle connections"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "idle in transcation" ],
         "text": "setAlias(idle in transcation)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: number of idle in transaction connections"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "disabled" ],
         "text": "setAlias(disabled)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL: number of disabled" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "aborted" ],
         "text": "setAlias(aborted)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: number of idle in transaction (aborted)"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Transactions commited/deadlocks/rollbacks (req/s)",
     "type": "graph",
     "description": "Transactions: commit rate, deadlocks, rollbacks",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 11 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "commited" ],
         "text": "setAlias(commited)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL transactions: total" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "deadlocks" ],
         "text": "setAlias(deadlocks)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL event: deadlocks" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "rollbacked" ],
         "text": "setAlias(rollbacked)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL event: rollbacks" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Tuples deleted/fetched/inserted/returned/updated (ops/sec)",
     "type": "graph",
     "description": "PostgreSQL tuples: deleted, fetched, inserted, returned",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "delta",
          "params": []
         },
         "params": [],
         "text": "delta()"
        },
        {
         "def": {
          "category": "Aggregate",
          "defaultParams": [
           "1m",
           "avg"
          ],
          "name": "aggregateBy",
          "params": [
           { "name": "interval", "type": "string" },
           {
            "name": "function",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "1m",
          "max"
         ],
         "text": "aggregateBy(1m, max)"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "deleted" ],
         "text": "setAlias(deleted)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL tuples: deleted" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "rate",
          "params": []
         },
         "params": [],
         "text": "rate()"
        },
        {
         "def": {
          "category": "Aggregate",
          "defaultParams": [
           "1m",
           "avg"
          ],
          "name": "aggregateBy",
          "params": [
           { "name": "interval", "type": "string" },
           {
            "name": "function",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "1m",
          "max"
         ],
         "text": "aggregateBy(1m, max)"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "fetched" ],
         "text": "setAlias(fetched)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL tuples: fetched" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "rate",
          "params": []
         },
         "params": [],
         "text": "rate()"
        },
        {
         "def": {
          "category": "Aggregate",
          "defaultParams": [
           "1m",
           "avg"
          ],
          "name": "aggregateBy",
          "params": [
           { "name": "interval", "type": "string" },
           {
            "name": "function",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "1m",
          "max"
         ],
         "text": "aggregateBy(1m, max)"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "inserted" ],
         "text": "setAlias(inserted)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL tuples: inserted" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "rate",
          "params": []
         },
         "params": [],
         "text": "rate()"
        },
        {
         "def": {
          "category": "Aggregate",
          "defaultParams": [
           "1m",
           "avg"
          ],
          "name": "aggregateBy",
          "params": [
           { "name": "interval", "type": "string" },
           {
            "name": "function",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "1m",
          "max"
         ],
         "text": "aggregateBy(1m, max)"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "returned" ],
         "text": "setAlias(returned)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL tuples: returned" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "rate",
          "params": []
         },
         "params": [],
         "text": "rate()"
        },
        {
         "def": {
          "category": "Aggregate",
          "defaultParams": [
           "1m",
           "avg"
          ],
          "name": "aggregateBy",
          "params": [
           { "name": "interval", "type": "string" },
           {
            "name": "function",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "1m",
          "max"
         ],
         "text": "aggregateBy(1m, max)"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "updated" ],
         "text": "setAlias(updated)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL tuples: updated" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Blocks hit/read (bytes)",
     "type": "graph",
     "description": "PostgreSQL blocks hit, read",
     "gridPos": { "h": 10, "w": 10, "x": 11, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "hit" ],
         "text": "setAlias(hit)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL blocks: hit" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "read" ],
         "text": "setAlias(read)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL blocks: read" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "PostgreSQL statements read/write/cpu io (time)",
     "type": "graph",
     "description": "PostgreSQL statements",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "read" ],
         "text": "setAlias(read)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL statements: read io time"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "write" ],
         "text": "setAlias(write)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL statements: write io time"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "other" ],
         "text": "setAlias(other)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL statements: other (mostly cpu) time"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "PostgreSQL statements read/write/others (bytes)",
     "type": "graph",
     "description": "PostgreSQL connections",
     "gridPos": { "h": 11, "w": 10, "x": 11, "y": 30 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "read" ],
         "text": "setAlias(read)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL statements: read bytes/s"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "write" ],
         "text": "setAlias(write)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL statements: write bytes/s"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "dirty" ],
         "text": "setAlias(dirty)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL statements: dirty bytes/s"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Temp files written (bytes)",
     "type": "graph",
     "description": "PostgreSQL temp files written",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "bytes written" ],
         "text": "setAlias(bytes written)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL temp: bytes written" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Blocks write (count)",
     "type": "graph",
     "description": "PostgreSQL bgwriter: buffers written during checkpoints, buffers written, number of bgwriter stopped by max write count, buffers written directly by a backend, times a backend execute its own fsync, buffers allocated",
     "gridPos": { "h": 10, "w": 10, "x": 11, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "buffers written" ],
         "text": "setAlias(buffers written)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL bgwriter: buffers written"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "buffers written by backend" ],
         "text": "setAlias(buffers written by backend)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL bgwriter: buffers written directly by a backend"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [
          "buffers written during checkpoints"
         ],
         "text": "setAlias(buffers written during checkpoints)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL bgwriter: buffers written during checkpoints"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Checkpoint by wal/timeout (count)",
     "type": "graph",
     "description": "PostgreSQL checkpoint",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "checkpoints by wal (in hour)" ],
         "text": "setAlias(checkpoints by wal (in hour))"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL checkpoints: by wal (in hour)"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [
          "checkpoints by timeout (in hour)"
         ],
         "text": "setAlias(checkpoints by timeout (in hour))"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL checkpoints: by timeout (in hour)"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "WAL write speed (bytes/sec)",
     "type": "graph",
     "description": "PostgreSQL: wal write speed",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 51 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "wal write speed" ],
         "text": "setAlias(wal write speed)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL: wal write speed" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Checkpoint write/sync time",
     "type": "graph",
     "description": "PostgreSQL checkpoint",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL checkpoint: write time"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL checkpoint: sync time"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Shared buffers (size, bytes)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 60 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "shared buffers" ],
         "text": "setAlias(shared buffers)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL: shared buffer size" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "shared buffers dirty" ],
         "text": "setAlias(shared buffers dirty)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: shared buffer dirty size"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "shared buffers twice used" ],
         "text": "setAlias(shared buffers twice used)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: shared buffer twice used size"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Autovacuum workers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "count of autovacuum workers" ],
         "text": "setAlias(count of autovacuum workers)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: count of autovacuum workers"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Streaming replication lag (time)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 69 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "rate",
          "params": []
         },
         "params": [],
         "text": "rate()"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Replication lag, sec" ],
         "text": "setAlias(Replication lag, sec)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Delta of total lag for .*/" },
       "itemids": "$env",
       "options": {
        "acknowledged": 2,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 0,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default"
       },
       "proxy": { "filter": "" },
       "showProblems": "problems",
       "slaInterval": "none",
       "slaProperty": { "name": "SLA", "property": "sla" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Relations size (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/^(Relation size: .*)/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Active queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active queries (from JSON)",
     "type": "table",
     "description": "This is the list of active requests extracted from the pg_stat_activity view. ",
     "gridPos": { "h": 13, "w": 22, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "select \n    tm,\n    query,\n    extract(epoch from(now() - (query_start::text)::timestamptz)) as duration\n-- Parse JSON\nfrom (\nSELECT\n    tm,\n    jsonb_path_query(datax::jsonb, '$[*].query ? ( (@ !=\"\")  && ( (@starts with \"select\") || (@starts with \"with\") || (@starts with \"update\") || (@starts with \"delete\") || (@starts with \"insert\") || (@starts with \"drop\") || (@starts with \"create\") ) )') as query,\n    jsonb_path_query(datax::jsonb, '$[*].query_start ? (@ != null)') as query_start,\n    jsonb_path_query(datax::jsonb, '$[*].datname ? (@ != \"\")') as datname\n    FROM\n        -- get 1 row in JSON format from Zabbix history_text table\n        (SELECT \n            q.clock as tm,\n            lower(q.value) as datax\n        FROM \n            public.items i \n        INNER JOIN public.hosts h\n        ON\n            (\n            h.hostid = i.hostid )\n        INNER JOIN \n            public.history_text q\n        ON \n            ( \n                i.itemid = q.itemid) \n        WHERE \n            h.name = '$host'\n            AND i.name = 'PostgreSQL: pg_stat_activity dump'\n            AND $__unixEpochFilter(q.clock)\n        order by q.clock desc\n        LIMIT 1) z ) x\nwhere datname::text ~ '$database'\nAND query != 'null'\norder by duration desc\nLIMIT $limit;"
      }
     ]
    }
   ]
  },
  {
   "title": "Query statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries stats (from JSON)",
     "type": "table",
     "description": "This is the list of active requests extracted from the pg_stat_activity view. ",
     "gridPos": { "h": 13, "w": 22, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT \n   query,\n   calls, \n   average,\n   rows_returned,\n   total,\n   cpu\n   FROM (\nSELECT \n   jsonb_path_query(data::jsonb, '$[*].query ? ( (@ != \"\") && ( (@starts with \"select\") || (@starts with \"with\") || (@starts with \"update\") || (@starts with \"delete\") || (@starts with \"insert\") || (@starts with \"drop\") || (@starts with \"create\") ) )') as query,\n   jsonb_path_query(data::jsonb, '$[*].calls ? (@ != null)') as calls,\n   jsonb_path_query(data::jsonb, '$[*]._avg ? (@ != null)') as average,\n   jsonb_path_query(data::jsonb, '$[*]._rows ? (@ != null)') as rows_returned,\n   jsonb_path_query(data::jsonb, '$[*]._time ? (@ != null)') as total,\n   jsonb_path_query(data::jsonb, '$[*]._cpu ? (@ != null)') as cpu\nFROM (\n  SELECT \n    lower(q.value) as data\n  FROM \n    public.items i \n  INNER JOIN public.hosts h\n  ON\n    (\n      h.hostid = i.hostid )\n  INNER JOIN \n    public.history_text q\n  ON \n    ( \n        i.itemid = q.itemid) \n  WHERE \n    h.name = '$host'\n    AND i.name = 'PostgreSQL: pg_stat_statements dump'\n    AND q.clock > EXTRACT(EPOCH FROM NOW()) - 10 * 60\n  ORDER BY q.clock DESC LIMIT 1) j) u\n  WHERE query is not null\n  order by cpu desc LIMIT $limit\n  ;"
      }
     ]
    }
   ]
  }
 ]
}