{
 "title": "PostgreSQL active queries: current state",
 "description": "Grafana dashboard for Mamonsu",
 "tags": [ "active" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": {}
   },
   {
    "name": "group",
    "label": "Group",
    "query": {}
   },
   {
    "name": "host",
    "label": "Host",
    "query": {}
   },
   {
    "name": "database",
    "label": "Database",
    "query": {}
   },
   { "name": "limit", "label": "Queries limit", "query": "5,10,15,20,30,40,50" }
  ]
 },
 "panels": [
  {
   "title": "Count of bloating tables",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Count of bloating tables in database: $database"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Sessions count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "PostgreSQL: pg_stat_activity sessions"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Idle",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "PostgreSQL: number of idle connections"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "PostgreSQL: number of active connections"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Idle in transaction",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "PostgreSQL: number of idle in transaction connections"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Wait queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wait queries: ${__from:date: DD MMM, kk.mm.ss A} – ${__to:date:DD MMM, kk.mm.ss A} ",
     "type": "table",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT\n   runtime,\n   datname,\n   usename,\n   wait_event,\n   wait_event_type,\n   query\n   FROM (\nSELECT\n   tm,\n   jsonb_path_query(datax::jsonb, '$[*].runtime ? (@ !=\"\")') as runtime,\n   jsonb_path_query(datax::jsonb, '$[*].datname ? (@ !=\"\")') as datname,\n   jsonb_path_query(datax::jsonb, '$[*].usename ? (@ !=\"\")') as usename,\n   jsonb_path_query(datax::jsonb, '$[*].wait_event ? (@ !=\"\")') as wait_event,\n   jsonb_path_query(datax::jsonb, '$[*].wait_event_type ? (@ !=\"\")') as wait_event_type,\n   jsonb_path_query(datax::jsonb, '$[*].query ? (@ !=\"\")') as query\n    FROM\n        -- get 1 row in JSON format from Zabbix history_text table\n        (\nSELECT \n    q.clock as tm,\n    lower(q.value) as datax\n  FROM \n    public.items i \n  INNER JOIN public.hosts h\n  ON\n    (\n      h.hostid = i.hostid )\n  INNER JOIN \n    public.history_text q\n  ON \n    ( \n        i.itemid = q.itemid) \n  WHERE \n    h.name = '$host'\n    AND i.name = 'PostgresSQL: pg_stat_activity wait queries'\n    AND $__unixEpochFilter(q.clock)\n    order by tm desc\n    limit 1\n  ) x ) y\n  WHERE datname::text ~ '$database'\n--  limit 10\n  limit $limit\n  ;"
      }
     ]
    }
   ]
  },
  {
   "title": "Active queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active queries: current state",
     "type": "table",
     "gridPos": { "h": 13, "w": 22, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n    datid,\n    datname,\n    pid,\n    leader_pid,\n    usesysid,\n    application_name,\n    client_addr,\n    client_hostname,\n    client_port,\n    backend_start,\n    xact_start,\n    query_start,\n    state_change,wait_event_type,wait_event,state,backend_xid,backend_xmin,backend_type,\n    query\nFROM \n    (   SELECT\n            tm,\n            jsonb_path_query(datax::jsonb, '$[*].datid ? (@ !=\"\")')            AS datid,\n            jsonb_path_query(datax::jsonb, '$[*].datname ? (@ !=\"\")')          AS datname,\n            jsonb_path_query(datax::jsonb, '$[*].pid ? (@ !=null)')              AS pid,\n            jsonb_path_query(datax::jsonb, '$[*].leader_pid ? (@ !=null)')       AS leader_pid,\n            jsonb_path_query(datax::jsonb, '$[*].usesysid ? (@ !=\"\")')         AS usesysid,\n            jsonb_path_query(datax::jsonb, '$[*].application_name ? (@ !=\"\")') AS application_name,\n            jsonb_path_query(datax::jsonb, '$[*].client_addr ? (@ !=\"\")')      AS client_addr,\n            jsonb_path_query(datax::jsonb, '$[*].client_hostname ? (@ !=\"\")')  AS client_hostname,\n            jsonb_path_query(datax::jsonb, '$[*].client_port ? (@ !=null)')      AS client_port,\n            jsonb_path_query(datax::jsonb, '$[*].backend_start ? (@ !=\"\")')    AS backend_start,\n            jsonb_path_query(datax::jsonb, '$[*].xact_start ? (@ !=\"\")')       AS xact_start,\n            jsonb_path_query(datax::jsonb, '$[*].query_start ? (@ !=\"\")')      AS query_start,\n            jsonb_path_query(datax::jsonb, '$[*].state_change ? (@ !=\"\")')     AS state_change,\n            jsonb_path_query(datax::jsonb, '$[*].wait_event_type ? (@ !=\"\")')  AS wait_event_type,\n            jsonb_path_query(datax::jsonb, '$[*].wait_event ? (@ !=\"\")')       AS wait_event,\n            jsonb_path_query(datax::jsonb, '$[*].state ? (@ !=\"\")')            AS state,\n            jsonb_path_query(datax::jsonb, '$[*].backend_xid ? (@ !=\"\")')     AS backend_xid,\n            jsonb_path_query(datax::jsonb, '$[*].backend_xmin ? (@ !=\"\")')     AS backend_xmin,\n            jsonb_path_query(datax::jsonb, '$[*].backend_type ? (@ !=\"\")')     AS backend_type,\n            jsonb_path_query(datax::jsonb, '$[*].query ? (@ !=\"\")')            AS query\n        FROM\n            -- get 1 row in JSON format from Zabbix history_text table\n            (   SELECT\n                    q.clock        AS tm,\n                    lower(q.value) AS datax\n                FROM\n                    public.items i\n                INNER JOIN \n                    public.hosts h\n                ON\n                    (\n                        h.hostid = i.hostid )\n                INNER JOIN\n                    public.history_text q\n                ON\n                    (\n                        i.itemid = q.itemid)\n                WHERE\n                    h.name = '$host'\n                AND i.name = 'PostgresSQL: pg_stat_activity active queries'\n                AND $__unixEpochFilter(q.clock)\n                order by tm desc\n                limit 1\n                ) x ) y\nWHERE \n  datname::TEXT ~ '$database'\nlimit $limit;"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections count per database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections count per database: ${__from:date: DD MMM, kk.mm.ss A} – ${__to:date:DD MMM, kk.mm.ss A} ",
     "type": "table",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\n   datname,\n   usename,\n   state,\n   cnt\n   FROM (\nSELECT\n   tm,\n   jsonb_path_query(datax::jsonb, '$[*].datname ? (@ !=\"\")') as datname,\n   jsonb_path_query(datax::jsonb, '$[*].usename ? (@ !=\"\")') as usename,\n   jsonb_path_query(datax::jsonb, '$[*].state ? (@ !=\"\")') as state,\n   jsonb_path_query(datax::jsonb, '$[*].count ? (@ !=null)') as cnt\n    FROM\n        -- get 1 row in JSON format from Zabbix history_text table\n        (\nSELECT \n    q.clock as tm,\n    lower(q.value) as datax\n  FROM \n    public.items i \n  INNER JOIN public.hosts h\n  ON\n    (\n      h.hostid = i.hostid )\n  INNER JOIN \n    public.history_text q\n  ON \n    ( \n        i.itemid = q.itemid) \n  WHERE \n    h.name = '$host'\n    AND i.name = 'PostgresSQL: pg_stat_activity connections count per database'\n    AND $__unixEpochFilter(q.clock)\n    order by tm desc\n    limit 1\n  ) x ) y\n  WHERE datname::text ~ '$database'\n--  limit 10\n  limit $limit\n  ;"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries locked",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries locked: current state",
     "type": "table",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\n    blocked_pid,\n    blocked_user,\n    blocked_client_addr,\n    blocked_client_hostname,\n    blocked_client_port,\n    blocked_application_name,\n    blocked_wait_event_type,\n    blocked_wait_event,\n    blocked_statement,\n    blocked_xact_start,\n    blocking_pid,\n    blocking_user,\n    blocking_user_addr,\n    blocking_client_hostname,\n    blocking_client_port,\n    blocking_application_name,\n    blocking_wait_event_type,\n    blocking_wait_event,\n    current_statement_in_blocking_process,\n    blocking_xact_start\nFROM \n    (   SELECT\n            tm,\n            jsonb_path_query(datax::jsonb, '$[*].blocked_pid ? (@ !=null)') AS blocked_pid,\n            jsonb_path_query(datax::jsonb, '$[*].blocked_user ? (@ !=\"\")') AS blocked_user,\n            jsonb_path_query(datax::jsonb, '$[*].blocked_client_addr ? (@ !=null)') AS blocked_client_addr,\n            jsonb_path_query(datax::jsonb, '$[*].blocked_client_hostname ? (@ !=\"\")') AS blocked_client_hostname,\n            jsonb_path_query(datax::jsonb, '$[*].blocked_client_port ? (@ !=null)') AS blocked_client_port,\n            jsonb_path_query(datax::jsonb, '$[*].blocked_application_name ? (@ !=\"\")')         AS blocked_application_name,\n            jsonb_path_query(datax::jsonb, '$[*].blocked_wait_event_type ? (@ !=\"\")') AS blocked_wait_event_type,\n            jsonb_path_query(datax::jsonb, '$[*].blocked_wait_event ? (@ !=\"\")')      AS blocked_wait_event,\n            jsonb_path_query(datax::jsonb, '$[*].blocked_statement ? (@ !=null)')  AS blocked_statement,\n            jsonb_path_query(datax::jsonb, '$[*].blocked_xact_start ? (@ !=\"\")')      AS blocked_xact_start,\n            jsonb_path_query(datax::jsonb, '$[*].backend_start ? (@ !=\"\")')    AS backend_start,\n            jsonb_path_query(datax::jsonb, '$[*].blocking_pid ? (@ !=null)')       AS blocking_pid,\n            jsonb_path_query(datax::jsonb, '$[*].blocking_user ? (@ !=\"\")')      AS blocking_user,\n            jsonb_path_query(datax::jsonb, '$[*].blocking_user_addr ? (@ !=\"\")')     AS blocking_user_addr,\n            jsonb_path_query(datax::jsonb, '$[*].blocking_client_hostname ? (@ !=\"\")')  AS blocking_client_hostname,\n            jsonb_path_query(datax::jsonb, '$[*].blocking_client_port ? (@ !=null)')       AS blocking_client_port,\n            jsonb_path_query(datax::jsonb, '$[*].blocking_application_name ? (@ !=\"\")')            AS blocking_application_name,\n            jsonb_path_query(datax::jsonb, '$[*].blocking_wait_event_type ? (@ !=\"\")')     AS blocking_wait_event_type,\n            jsonb_path_query(datax::jsonb, '$[*].blocking_wait_event ? (@ !=\"\")')     AS blocking_wait_event,\n            jsonb_path_query(datax::jsonb, '$[*].current_statement_in_blocking_process ? (@ !=\"\")')     AS current_statement_in_blocking_process,\n            jsonb_path_query(datax::jsonb, '$[*].blocking_xact_start ? (@ !=\"\")')            AS blocking_xact_start\n        FROM\n        -- get 1 row in JSON format from Zabbix history_text table\n        (\nSELECT \n    q.clock as tm,\n    lower(q.value) as datax\n  FROM \n    public.items i \n  INNER JOIN public.hosts h\n  ON\n    (\n      h.hostid = i.hostid )\n  INNER JOIN \n    public.history_text q\n  ON \n    ( \n        i.itemid = q.itemid) \n  WHERE \n    h.name = '$host'\n    AND i.name = 'PostgresSQL: pg_stat_activity queries locked'\n    AND $__unixEpochFilter(q.clock)\n    order by tm desc\n    limit 1\n  ) x ) y\n--  limit 10\n  limit $limit\n  ;"
      }
     ]
    }
   ]
  }
 ]
}