---
- hosts: '{{ target | default("postgres") }}'
  gather_facts: true
  pre_tasks:
    - name: Make selinux permissive
      selinux:
        policy: targeted
        state: permissive
      become: yes

    - name: Install PostgreSQL repository
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
      become: yes

  tasks:
    - name: Install pgbackrest
      yum:
        name: pgbackrest
        state: present
      become: yes

  # roles:
  #   - role: ansible-role-pgbackrest
  #     ignore_errors: true
  #     become: yes
